name: 'Check log with reviewdog'
description: 'Find log method of golang functions with reviewdog'
author: 'seipan'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
    default: ${{ github.token }}
  workdir:
    description: 'working directory relative to the root directory'
    required: false
    default: ./

runs:
  using: 'composite'
  steps:
    - run: go install github.com/seipan/logfind/cmd/logfind
      shell: bash
    - name: Setup reviewdog
      run: |
        INSTALL_SHELL=https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh
        mkdir -p $HOME/bin && curl -sfL $INSTALL_SHELL| sh -s -- -b $HOME/bin
        echo "$HOME/bin" >> $GITHUB_PATH
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH # for Go projects
      shell: bash
    - run: ${{ github.action_path }}/server/reviewdog/reviewdog.sh
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_WORKDIR: ${{ inputs.workdir }}
      shell: bash