export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="font-mono">
        <p>fhdalskhflk</p>
        {children}
      </body>
    </html>
  );
}
