## Build
FROM golang:1.19-buster AS build

WORKDIR /go/src/github.com/Doer-org/glyph

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

RUN go build -o /docker-gs-ping ./cmd/migrate/main.go

## Deploy
FROM gcr.io/distroless/base-debian10

COPY --from=build /docker-gs-ping /docker-gs-ping

ENTRYPOINT ["/docker-gs-ping"]