name: lint
on:
  push:
    branches:
      - dev
  pull_request:

permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
   steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          args: --enable=gosec,prealloc,gocognit