name: lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
jobs:
  golangci:
   name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read Go version
        run: echo "GO_VERSION=$(cat .server/.go-version)" >> $GITHUB_ENV
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: '--timeout 3m0s'