name: lint
on:
  push:
    branches:
      - dev
  pull_request:

permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - uses: actions/checkout@v3
      - name : pwd
        run: pwd
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest