name: lint
on:
  push:
    paths:
     - .github/**
     - server/**
    branches: [ "dev","main" ]
  pull_request:
    paths:
     - .github/**
     - server/**
    branches: [ "dev","main" ]
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          cache: false
      - uses: actions/checkout@v3
      - name: pwd
        run: pwd
      - name: ls
        run: ls
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29